### ISSUE TITLE
[PE-D][Tester D] Schedule multiple clients with same date time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#127]
### What Happened:
After entering `schedule 1 d/2024-07-08 07:30` followed by `schedule 2 d/2024-07-08 07:30`,
I realised that I can schedule multiple clients with same date time:

![image.png](https://raw.githubusercontent.com/ziyi22/ped/main/files/b701a495-86b7-420c-8903-3c61597323bf.png)

### Suggestion:
It would be better to prevent scheduling multiple clients with the same date and time.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ziyi22/ped#2

**Comment by getsquared** [comment]
Duplicate with #130
