### ISSUE TITLE
[PE-D][Tester C] Hard to see index of schedule list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#131]
![image.png](https://raw.githubusercontent.com/xuwen-ho/ped/main/files/cfca2bfc-ab42-427b-a2b9-750b1f51e032.png)

When using the mark command to remove appointments that have occurred, we need to specify index which is difficult to see if there are a lot of appointments. Can improve by specifying index.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xuwen-ho/ped#4

**Comment by getsquared** [comment]
The index can be referred to on the left in the client list
If there are many clients, the user can use find to search the name that is in the schedule panel to get the index
