### ISSUE TITLE
[PE-D][Tester C] Duplicate Policies IDs allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#134]
![image.png](https://raw.githubusercontent.com/xuwen-ho/ped/main/files/f254fe89-a76d-4f98-ba70-74f668c7f627.png)

I can add a policy ID of 1 when one of 001 exists. I would say the 2 should be considered equivalent IDs.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: xuwen-ho/ped#5

**Comment by ReganChoy** [comment]
001 and 1 are not duplicated policy IDs as different insurance companies have different numbering schemes.
