### ISSUE TITLE
[PE-D][Tester C] remark replaces current remark

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-1/tp#136]
![image.png](https://raw.githubusercontent.com/xuwen-ho/ped/main/files/88d59bd0-5699-44f0-bb77-6a990ec6fa60.png)

When I execute the remark command and there is already an existing remark command, it replaces the previous remark. Might be problematic because if i wish to update it, i would have to type everything that was there before.

Maybe can implement more of an append feature for remark.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xuwen-ho/ped#6

**Comment by getsquared** [comment]
Duplicate with #141

**Comment by getsquared** [comment]
Not allowed to fix
