### ISSUE TITLE
[PE-D][Tester A] Unexpected behaviour when index is greater than Integer.MAX_INT

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-1/tp#143]
Description:
  - For commands such as edit, delete etc that takes in an index, the error message changes when a number exceeding MAX_INT is given. This should not be the case and the error message should consistently prompt "The client index provided is not on the list!".

Replication:
  - Start up with default json file.
  - Enter commands:
      - mark 10
  - Observe that the error message is "The client index provided is not on the list!"
  - Enter commands:
      - mark 3000000000
  - Observe that the error message changes to "Invalid command format!"

Negative Impact:
  - If the user enters a valid command but with an extra large index, it will be very confusing for them if the system prompts "Invalid command format!". Instead a more accurate error message should be given.

Suggested Solution:
  - Edit error message for when index exceeds MAX_INT

Screenshots:

![Screenshot 2024-04-05 at 4.58.06 PM.png](https://raw.githubusercontent.com/alfaloo/ped/main/files/f36320c6-2c89-4af2-b848-b68b82a17f64.png)

![Screenshot 2024-04-05 at 4.58.20 PM.png](https://raw.githubusercontent.com/alfaloo/ped/main/files/ad230a65-e0b8-40c5-867f-338c577a274b.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: alfaloo/ped#7

**Comment by yorklim** [comment]
Integer Limit Issue

**Comment by getsquared** [comment]
Duplicate with #167 and #157
