### ISSUE TITLE
[PE-D][Tester A] Can bypass the uniqueness of names.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#145]
Description:
  - The user guide explicitly states that client's names should be unique. However, "John Doe", "john doe", and. "John   Doe" can all simultaneously exist in the system.

Replication:
  - Start up with default json file.
  - Enter commands:
      - add n/John Doe c/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 d/1990-01-01 p/low
      - add n/john doe c/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 d/1990-01-01 p/low
      - add n/John   Doe c/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 d/1990-01-01 p/low

Negative Impact:
  - As users, sometimes it is difficult to make sure we always capitalise / don't capitalise names of our clients. Thus this easily bypasses the requirement that clients in the system are unique.

Suggested Solution:
  - Implement a more robust name matcher to ensure that users can not bypass the uniqueness of names.

Screenshots:

![Screenshot 2024-04-05 at 5.03.51 PM.png](https://raw.githubusercontent.com/alfaloo/ped/main/files/23997eec-b0f5-448c-98cd-2e6a495ce457.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: alfaloo/ped#8

**Comment by getsquared** [comment]
Fixed in #177
