### ISSUE TITLE
[PE-D][Tester A] Unrealistic constraint on the name parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#146]
Description:
  - When adding a new client, their name can be just numbers, e.g. 12345. This is clearly an invalid name and the user should be met with an error message.

Replication:
  - Start up with default json file.
  - Enter commands:
      - add n/12345 c/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 d/1990-01-01 p/low

Negative Impact:
  - If the user confuses the phone number field with the name field, then they might accidentally enter the client's phone number in the name field and the system will accept the inputs even though it is not a correct name.

Suggested Solution:
  - Only allow alphabetical letters and white space for names.

Screenshots:

![Screenshot 2024-04-05 at 5.10.20 PM.png](https://raw.githubusercontent.com/alfaloo/ped/main/files/4dd54e26-a42e-4d01-a4cc-d570a86c015b.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: alfaloo/ped#9

**Comment by yorklim** [comment]
Tell that to elon musk :D

**Comment by getsquared** [comment]
Duplicate with #133
