### ISSUE TITLE
[PE-D][Tester D] Failed open jar file

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#151]
### Expected:

![image.png](https://raw.githubusercontent.com/ziyi22/ped/main/files/06c3a50f-d842-4c4d-88f5-6226f1bf6bee.png)

### Actual: 
An error occurred when following the instruction in the user guide to open jar file.
![image.png](https://raw.githubusercontent.com/ziyi22/ped/main/files/094007ce-a4c8-461c-a332-b564d2412dd3.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ziyi22/ped#5

**Comment by ReganChoy** [comment]
Tester would have clicked the blue hyperlink to see the alternative ways to open the app. The alternative ways will definitely work as they employ the use of CLI to start the app. Hence, this is not a bug as tester did not test all the other ways to open the app.

![image](https://github.com/AY2324S2-CS2103T-W12-1/tp/assets/122202019/0e247b69-66fb-446b-baf2-f81bfc9b596c)

**Comment by yorklim** [comment]
Drop us an email if the problem persist after trying the alternative start up methods
