### ISSUE TITLE
[PE-D][Tester D] Email Constraint Problem

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#160]
### What I did: 
![image.png](https://raw.githubusercontent.com/ziyi22/ped/main/files/5fed9805-82bf-486c-bf4d-c57ab28a47b3.png)
I input the 'local-part' of the email followed by the returned message where:
- only contain alphanumeric characters and these special characters, 
- excluding the parentheses
- not start or end with any special characters

### Expected: 
edit email successfully

### Actual:
But encountered constraint error

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ziyi22/ped#10

**Comment by getsquared** [comment]
Fixed in #179
