### ISSUE TITLE
[PE-D][Tester A] Inconsistent scroll bar visuals

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#165]
Description:
  - The scroll bar for the central client panel is surrounded by a light grey border whereas this border is not present in any of the other scroll bars around the GUI.

Replication:
  - Start up with default json file.
  - Observe that difference in scroll bar visuals between the one located in the left contacts panel and the one in the central client panel.

Negative Impact:
  - Can be somewhat distracting for users. This inconsistency might also trigger OCD in some users.

Suggested Solution:
  - Maybe remove any padding that is currently set on the scroll bar hbox in javafx.

Screenshots:

![Screenshot 2024-04-05 at 9.04.17 PM.png](https://raw.githubusercontent.com/alfaloo/ped/main/files/ddf61989-8418-4863-a1b3-ff4e3499cca2.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: alfaloo/ped#16

**Comment by yorklim** [comment]
User preference Issue
