### ISSUE TITLE
[PE-D][Tester B] Inability to add a new client without some parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#169]
Sometimes due to privacy concerns, or lack of time, users might want to be able to **add a new member without** asking for all their details like **email, address and especially birthday**! As such, it might be better to allow users to add members without making all the fields compulsory. Name and phone number should be kept compulsory, but the rest can be reconsidered!

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: billyhoce/ped#6

**Comment by yorklim** [comment]
Dummy values can be put in and when signing a policy client would provide these information already

**Comment by getsquared** [comment]
Added workaround to UG in #179
