### ISSUE TITLE
[PE-D][Tester B] Grammatical error in error message of addpolicy and deletepolicy

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-1/tp#171]
The error message produced by having an invalid Policy ID parameter for both addpolicy and deletepolicy should be "...at least 1 digit long" (No "s" behind digit)

![image.png](https://raw.githubusercontent.com/billyhoce/ped/main/files/4cddc8da-b6af-498c-a3c2-3bf50c5e02b6.png)

![image.png](https://raw.githubusercontent.com/billyhoce/ped/main/files/9838bada-bc27-4a9e-b990-f2108ef0e820.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: billyhoce/ped#8

**Comment by ReganChoy** [comment]
Very minor but good catch nevertheless

**Comment by getsquared** [comment]
Fixed in #174
