### ISSUE TITLE
Add Policy

### ISSUE THREAD

**Issue by ReganChoy** [AY2324S2-CS2103T-W12-1/tp#44]
As an insurance agent, I want to be able to add policies to my clients, so I can keep track of my client's policies.

**Comment by yorklim** [comment]
- Added AddPolicy Command and parser on local repo
- Constructor for person and updated EditCommand, LastMetCommand, MarkCommand, ScheduleCommand
- Included command into AddressBook Parser

Todo:
- Make Policies show on GUI
- Testing
